
%OPPGAVE4 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 14-Nov-2017 15:16:24

% FIR Window Bandstop filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 22050;  % Sampling Frequency

N    = 370;        % Order
Fc1  = 4650;       % First Cutoff Frequency
Fc2  = 5350;       % Second Cutoff Frequency
flag = 'noscale';  % Sampling Flag

% Create the window vector for the design algorithm.
win = hamming(N+1);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'stop', win, flag);
Hd = dfilt.dffir(b);


% [EOF]
