function Hd = testpass
%TESTPASS Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 14-Nov-2017 15:33:56

% Equiripple Bandstop filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 22050;  % Sampling Frequency

N      = 200;    % Order
Fpass1 = 7200;   % First Passband Frequency
Fstop1 = 9600;   % First Stopband Frequency
Fstop2 = 10000;  % Second Stopband Frequency
Fpass2 = 11000;  % Second Passband Frequency
Wpass1 = 1;      % First Passband Weight
Wstop  = 1;      % Stopband Weight
Wpass2 = 1;      % Second Passband Weight
dens   = 20;     % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass1 Fstop1 Fstop2 Fpass2 Fs/2]/(Fs/2), [1 1 0 0 1 ...
           1], [Wpass1 Wstop Wpass2], {dens});
Hd = dfilt.dffir(b);

% [EOF]
